services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9999:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - Username=tactik8
      - Password=Temp4now
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      ## The left part is the path on your host, the right part is the path in the stash container.

      ## Keep configs, scrapers, and plugins here.
      - /mnt/nas4/dockers/stash/config:/root/.stash
      ## Point this at your collection.
      ## The left side is where your collection is on your host, the right side is where it will be in stash.
      - /mnt/nas4/media2:/data
      ## This is where your stash's metadata lives
      - /mnt/nas4/dockers/stash/metadata:/metadata
      ## Any other cache content.
      - /mnt/nas4/dockers/stash/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /mnt/nas4/dockers/stash/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /mnt/nas4/dockers/stash/generated:/generated
     
  yt-dlp:
    image: marcobaobao/yt-dlp-webui:latest
    container_name: yt-dlp-webui
    restart: unless-stopped
    ports:
      - "3033:3033"
    volumes:
      # Use the same 'downloads' folder as Stash
      - /mnt/nas4/dockers/stash/downloads:/downloads
      - /mnt/nas4/dockers/stash/yt-dlp-config:/config
     
