services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - /mnt/nas4/dockers/uptime-kuma/data_server:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "30002:3001"



